require conf/distro/poky.conf

DISTRO = "piconsole"
DISTRO_NAME = "Pi Console"
DISTRO_VERSION = "0.1"

DISTRO_FEATURES:append = " systemd wayland opengl pam usrmerge wifi bluez5 rauc"
DISTRO_FEATURES:remove = "x11"

VIRTUAL-RUNTIME_init_manager = "systemd"
VIRTUAL-RUNTIME_initscripts = ""

PACKAGE_CLASSES ?= "package_rpm"
USER_CLASSES ?= "buildstats"
PATCHRESOLVE = "noop"
