export component SystemSettingsView inherits Rectangle {
    in property <bool> wifi-enabled: false;
    in property <bool> bluetooth-enabled: false;
    in property <int> selected-index;
    in property <bool> focused: false;  
    in property <string> status-text: "";

    in property <length> item-spacing: 20px;
    in property <length> item-height: 120px;
    in property <length> item-width: 600px;
    in property <length> item-radius: 30px;
    in property <length> start-y: 160px;

    callback toggle_wifi(); 
    callback toggle_bluetooth();

    background: #292929;


    Text {
        y: 72px;
        width: parent.width;
        text: "System";
        color: #f4f7f5;
        font-size: 42px;
        font-weight: 800;
        horizontal-alignment: center;
    }


    // WiFi Module
    Rectangle {
        x: parent.width / 2 - root.item-width / 2;
        y: root.start-y;
        visible: true;
        width: root.item-width;
        height: root.item-height; 
        border-radius: 30px;
        clip: false;

        background: root.focused && root.selected-index == 0 ? #ffffff : #15181d;

        Text { x: 28px; y: 32px; text: "WiFi Module"; color: root.focused && root.selected-index == 0 ? #000000 : #eef2ef; font-size: 20px; font-weight: 700; }
        Text { x: parent.width - 118px; y: 28px; text: root.wifi-enabled ? "Enabled" : "Disabled"; color: root.wifi-enabled ? #1db954 : #8f9993; font-size: 18px; font-weight: 700; horizontal-alignment: right; }
        Text { x: 28px; y: 60px; text: "Enable the wireless network service chip. After enabling go to settings and select network to configure your connection."; color: root.focused && root.selected-index == 0 ? #8f9993 : #5a5a5a; font-size: 13px; width: parent.width - 256px; wrap: word-wrap; }
        TouchArea { clicked => { root.toggle_wifi(); } }

    }

    // Bluetooth Module
    Rectangle {
        x: parent.width / 2 - root.item-width / 2;
        y: root.start-y + (1 * (root.item-height + root.item-spacing));
        width: root.item-width;
        height: root.item-height;
        background:  root.focused && root.selected-index == 1 ? #ffffff : #15181d;
        border-radius: 30px;

        Text { x: 28px; y: 26px; text: "Bluetooth Module"; color: root.focused && root.selected-index == 1 ? #000000 : #eef2ef; font-size: 20px; font-weight: 700; }
        Text { x: parent.width - 118px; y: 28px; text: root.bluetooth-enabled ? "Enabled" : "Disabled"; color: root.bluetooth-enabled ? #1db954 : #8f9993; font-size: 18px; font-weight: 700; horizontal-alignment: right; }
        Text { x: 28px; y: 60px; text: "Enable the Bluetooth chip."; color: root.focused && root.selected-index == (root.wifi-enabled ? 2 : 1) ? #8f9993 : #5a5a5a; font-size: 13px; }
        TouchArea { clicked => { root.toggle_bluetooth(); } }

    }
 
    
    
}