d /data/games 0755 pi pi -
d /data/games/project 0755 root root -
d /data/games/project/openconsole 0755 root root -
d /data/downloads 0755 pi pi -
d /data/configs 0755 pi pi -
d /data/saves 0755 pi pi -
d /data/screenshots 0755 pi pi -
d /data/logs 0755 pi pi -
d /data/cache 0755 pi pi -
d /data/home 0755 root root -
d /data/home/root 0700 root root -
d /data/home/root/.cache 0700 root root -
d /data/home/root/.config 0700 root root -
d /data/home/root/.local 0700 root root -
d /data/home/root/.local/share 0700 root root -
d /data/home/pi 0755 pi pi -
d /data/home/pi/.cache 0700 pi pi -
d /data/home/pi/.config 0700 pi pi -
d /data/home/pi/.local 0700 pi pi -
d /data/home/pi/.local/share 0700 pi pi -
f /data/openconsole-launch.log 0664 root root -
f /data/openconsole-supervisor-systemd.log 0664 root root -
f /data/openconsole-ui-current.log 0664 root root -
f /data/openconsole-ui-previous.log 0664 root root -
f /data/godot-current.log 0664 root root -
f /data/godot-previous.log 0664 root root -